// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlcgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    file_id,
    subject_id,
    user_id,
    name,
    storage_path,
    mime_type,
    size_bytes,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING file_id, subject_id, user_id, name, storage_path, mime_type, size_bytes, status, error_message, uploaded_at, processed_at
`

type CreateFileParams struct {
	FileID      uuid.UUID  `json:"file_id"`
	SubjectID   uuid.UUID  `json:"subject_id"`
	UserID      uuid.UUID  `json:"user_id"`
	Name        string     `json:"name"`
	StoragePath string     `json:"storage_path"`
	MimeType    string     `json:"mime_type"`
	SizeBytes   int64      `json:"size_bytes"`
	Status      FileStatus `json:"status"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.FileID,
		arg.SubjectID,
		arg.UserID,
		arg.Name,
		arg.StoragePath,
		arg.MimeType,
		arg.SizeBytes,
		arg.Status,
	)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorMessage,
		&i.UploadedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE file_id = $1
  AND user_id = $2
`

type DeleteFileParams struct {
	FileID uuid.UUID `json:"file_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.FileID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one

SELECT file_id, subject_id, user_id, name, storage_path, mime_type, size_bytes, status, error_message, uploaded_at, processed_at
FROM files
WHERE file_id = $1
`

// sql/queries/files.sql
func (q *Queries) GetFileByID(ctx context.Context, fileID uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, fileID)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorMessage,
		&i.UploadedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getFileByIDAndUserID = `-- name: GetFileByIDAndUserID :one
SELECT file_id, subject_id, user_id, name, storage_path, mime_type, size_bytes, status, error_message, uploaded_at, processed_at
FROM files
WHERE file_id = $1
  AND user_id = $2
`

type GetFileByIDAndUserIDParams struct {
	FileID uuid.UUID `json:"file_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFileByIDAndUserID(ctx context.Context, arg GetFileByIDAndUserIDParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByIDAndUserID, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorMessage,
		&i.UploadedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listFilesBySubjectID = `-- name: ListFilesBySubjectID :many
SELECT file_id, subject_id, user_id, name, storage_path, mime_type, size_bytes, status, error_message, uploaded_at, processed_at
FROM files
WHERE subject_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListFilesBySubjectID(ctx context.Context, subjectID uuid.UUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesBySubjectID, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.FileID,
			&i.SubjectID,
			&i.UserID,
			&i.Name,
			&i.StoragePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.Status,
			&i.ErrorMessage,
			&i.UploadedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileStatus = `-- name: UpdateFileStatus :one
UPDATE files
SET
    status        = $2,
    error_message = $3,
    processed_at  = CASE
                        WHEN $2::file_status = 'ready' THEN NOW()
                        ELSE processed_at
                    END
WHERE file_id = $1
RETURNING file_id, subject_id, user_id, name, storage_path, mime_type, size_bytes, status, error_message, uploaded_at, processed_at
`

type UpdateFileStatusParams struct {
	FileID       uuid.UUID      `json:"file_id"`
	Status       FileStatus     `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileStatus, arg.FileID, arg.Status, arg.ErrorMessage)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorMessage,
		&i.UploadedAt,
		&i.ProcessedAt,
	)
	return i, err
}
