// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createIngestJob = `-- name: CreateIngestJob :one

INSERT INTO ingest_jobs (job_id, file_id, status, max_retries)
VALUES ($1, $2, $3, $4)
RETURNING job_id, file_id, status, retry_count, max_retries, error_message, created_at, started_at, completed_at
`

type CreateIngestJobParams struct {
	JobID      uuid.UUID `json:"job_id"`
	FileID     uuid.UUID `json:"file_id"`
	Status     JobStatus `json:"status"`
	MaxRetries int32     `json:"max_retries"`
}

// sql/queries/ingest_jobs.sql
func (q *Queries) CreateIngestJob(ctx context.Context, arg CreateIngestJobParams) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, createIngestJob,
		arg.JobID,
		arg.FileID,
		arg.Status,
		arg.MaxRetries,
	)
	var i IngestJob
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIngestJobByFileID = `-- name: GetIngestJobByFileID :one
SELECT job_id, file_id, status, retry_count, max_retries, error_message, created_at, started_at, completed_at
FROM ingest_jobs
WHERE file_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// 最新の ingest_job を取得（ファイルのステータス確認用）
func (q *Queries) GetIngestJobByFileID(ctx context.Context, fileID uuid.UUID) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, getIngestJobByFileID, fileID)
	var i IngestJob
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIngestJobByID = `-- name: GetIngestJobByID :one
SELECT job_id, file_id, status, retry_count, max_retries, error_message, created_at, started_at, completed_at
FROM ingest_jobs
WHERE job_id = $1
`

func (q *Queries) GetIngestJobByID(ctx context.Context, jobID uuid.UUID) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, getIngestJobByID, jobID)
	var i IngestJob
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateIngestJobStatus = `-- name: UpdateIngestJobStatus :one
UPDATE ingest_jobs
SET
    status        = $2,
    error_message = $3,
    started_at    = CASE
                        WHEN $2::job_status = 'processing' THEN NOW()
                        ELSE started_at
                    END,
    completed_at  = CASE
                        WHEN $2::job_status IN ('completed', 'failed') THEN NOW()
                        ELSE completed_at
                    END,
    retry_count   = CASE
                        WHEN $2::job_status = 'failed' THEN retry_count + 1
                        ELSE retry_count
                    END
WHERE job_id = $1
RETURNING job_id, file_id, status, retry_count, max_retries, error_message, created_at, started_at, completed_at
`

type UpdateIngestJobStatusParams struct {
	JobID        uuid.UUID      `json:"job_id"`
	Status       JobStatus      `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateIngestJobStatus(ctx context.Context, arg UpdateIngestJobStatusParams) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, updateIngestJobStatus, arg.JobID, arg.Status, arg.ErrorMessage)
	var i IngestJob
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
