// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package sqlcgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (subject_id, user_id, name, lms_course_id)
VALUES ($1, $2, $3, $4)
RETURNING subject_id, user_id, name, lms_course_id, created_at, updated_at
`

type CreateSubjectParams struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject,
		arg.SubjectID,
		arg.UserID,
		arg.Name,
		arg.LmsCourseID,
	)
	var i Subject
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects
WHERE subject_id = $1
  AND user_id    = $2
`

type DeleteSubjectParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSubject(ctx context.Context, arg DeleteSubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, arg.SubjectID, arg.UserID)
	return err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT subject_id, user_id, name, lms_course_id, created_at, updated_at
FROM subjects
WHERE subject_id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, subjectID uuid.UUID) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByID, subjectID)
	var i Subject
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectByIDAndUserID = `-- name: GetSubjectByIDAndUserID :one
SELECT subject_id, user_id, name, lms_course_id, created_at, updated_at
FROM subjects
WHERE subject_id = $1
  AND user_id    = $2
`

type GetSubjectByIDAndUserIDParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSubjectByIDAndUserID(ctx context.Context, arg GetSubjectByIDAndUserIDParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByIDAndUserID, arg.SubjectID, arg.UserID)
	var i Subject
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectsByUserID = `-- name: ListSubjectsByUserID :many

SELECT subject_id, user_id, name, lms_course_id, created_at, updated_at
FROM subjects
WHERE user_id = $1
ORDER BY created_at DESC
`

// sql/queries/subjects.sql
func (q *Queries) ListSubjectsByUserID(ctx context.Context, userID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.SubjectID,
			&i.UserID,
			&i.Name,
			&i.LmsCourseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubjectName = `-- name: UpdateSubjectName :one
UPDATE subjects
SET name       = $2,
    updated_at = NOW()
WHERE subject_id = $1
  AND user_id    = $3
RETURNING subject_id, user_id, name, lms_course_id, created_at, updated_at
`

type UpdateSubjectNameParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	Name      string    `json:"name"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateSubjectName(ctx context.Context, arg UpdateSubjectNameParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, updateSubjectName, arg.SubjectID, arg.Name, arg.UserID)
	var i Subject
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
