# ============================================================
# eduanimaR — Cloud Build パイプライン
#
# トリガー: main ブランチへの push
# ビルド順: librarian → professor → frontend（依存関係順）
#
# 使い方（手動実行）:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_REGION=asia-northeast1,_REPO=eduanima
#
# 必要な Secret Manager シークレット:
#   - GEMINI_API_KEY  （Cloud Build サービスアカウントに secretAccessor 権限が必要）
# ============================================================

substitutions:
  # ビルド対象リージョン・Artifact Registry リポジトリ
  _REGION: asia-northeast1
  _REPO: eduanima
  # Cloud Run サービス名
  _SVC_FRONTEND: eduanima-frontend
  _SVC_PROFESSOR: eduanima-professor
  _SVC_LIBRARIAN: eduanima-librarian
  # Cloud SQL（PostgreSQL + pgvector）接続名
  _CLOUDSQL_INSTANCE: ${PROJECT_ID}:${_REGION}:eduanima-postgres
  # Next.js ビルド時の公開 URL
  _NEXT_PUBLIC_API_BASE_URL: https://api.eduanima.example.com/api

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY

steps:
  - id: lint-no-bitnami
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if grep -R --line-number -i -E "(bitnami|bitnamilegacy)" .; then
          echo "❌ Forbidden image reference found (bitnami|bitnamilegacy)."; exit 1;
        else
          echo "✅ no forbidden image references";
        fi

  # ════════════════════════════════════════════════════════════
  # 1. Librarian（Python gRPC）— runtime イメージをビルド
  # ════════════════════════════════════════════════════════════
  - id: build-librarian
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --target=runtime
      - --cache-from=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_LIBRARIAN}:latest
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_LIBRARIAN}:$SHORT_SHA
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_LIBRARIAN}:latest
      - ./eduanimaR_Librarian

  - id: push-librarian
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_LIBRARIAN}
    waitFor: [build-librarian]

  # ════════════════════════════════════════════════════════════
  # 2. Professor（Go バックエンド）— production イメージをビルド
  # ════════════════════════════════════════════════════════════
  - id: build-professor
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --target=production
      - --cache-from=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_PROFESSOR}:latest
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_PROFESSOR}:$SHORT_SHA
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_PROFESSOR}:latest
      - ./eduanimaR_Professor

  - id: push-professor
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_PROFESSOR}
    waitFor: [build-professor]

  # ════════════════════════════════════════════════════════════
  # 3. Frontend（Next.js standalone）— production イメージをビルド
  # ════════════════════════════════════════════════════════════
  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --target=production
      - --build-arg=NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}
      - --cache-from=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_FRONTEND}:latest
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_FRONTEND}:$SHORT_SHA
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_FRONTEND}:latest
      - ./eduanimaR

  - id: push-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_FRONTEND}
    waitFor: [build-frontend]

  # ════════════════════════════════════════════════════════════
  # 4. Cloud Run デプロイ — Librarian（内部のみ）
  # ════════════════════════════════════════════════════════════
  - id: deploy-librarian
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SVC_LIBRARIAN}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_LIBRARIAN}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --port=50051
      # ⚠️ Librarian はインターネット非公開（Professor からの内部通信のみ）
      - --ingress=internal
      - --allow-unauthenticated=false
      - --min-instances=1
      - --max-instances=5
      - --memory=1Gi
      - --cpu=1
      - --set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest
      - --set-env-vars=LOG_LEVEL=info,LIBRARIAN_MODEL_FAST=gemini-2.0-flash
    waitFor: [push-librarian]

  # ════════════════════════════════════════════════════════════
  # 5. Cloud Run デプロイ — Professor（Load Balancer 経由のみ）
  # ════════════════════════════════════════════════════════════
  - id: deploy-professor
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SVC_PROFESSOR}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_PROFESSOR}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --port=8080
      # Load Balancer 経由のみ許可（インターネットから直接は不可）
      - --ingress=internal-and-cloud-load-balancing
      - --allow-unauthenticated
      - --min-instances=1
      - --max-instances=10
      - --memory=512Mi
      - --cpu=1
      - --add-cloudsql-instances=${_CLOUDSQL_INSTANCE}
      - --set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest
      - --set-env-vars=PORT=8080,OBJECT_STORAGE_BACKEND=gcs,LOG_LEVEL=info
    waitFor: [push-professor, deploy-librarian]

  # ════════════════════════════════════════════════════════════
  # 6. Cloud Run デプロイ — Frontend（Load Balancer 経由のみ）
  # ════════════════════════════════════════════════════════════
  - id: deploy-frontend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SVC_FRONTEND}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_FRONTEND}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --port=3000
      # Load Balancer 経由のみ許可
      - --ingress=internal-and-cloud-load-balancing
      - --allow-unauthenticated
      - --min-instances=1
      - --max-instances=10
      - --memory=512Mi
      - --cpu=1
      - --set-env-vars=NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1
    waitFor: [push-frontend, deploy-professor]

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_LIBRARIAN}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_PROFESSOR}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SVC_FRONTEND}:$SHORT_SHA
