// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunks.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const deleteChunksByFileID = `-- name: DeleteChunksByFileID :exec
UPDATE materials
SET is_active = FALSE,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE raw_file_id = $1
  AND is_active = TRUE
`

func (q *Queries) DeleteChunksByFileID(ctx context.Context, rawFileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByFileID, rawFileID)
	return err
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO materials (
  id,
  raw_file_id,
  sequence_in_file,
  page_start,
  page_end,
  content_markdown,
  char_count,
  embedding
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $4,
  $5,
  char_length($5),
  $6
)
RETURNING
  id AS chunk_id,
  raw_file_id AS file_id,
  (SELECT subject_id FROM raw_files WHERE id = raw_file_id) AS subject_id,
  page_start AS page_number,
  sequence_in_file AS chunk_index,
  content_markdown AS content,
  embedding,
  created_at
`

type InsertChunkParams struct {
	ChunkID    uuid.UUID       `json:"chunk_id"`
	FileID     uuid.UUID       `json:"file_id"`
	ChunkIndex int32           `json:"chunk_index"`
	PageNumber sql.NullInt32   `json:"page_number"`
	Content    string          `json:"content"`
	Embedding  pgvector.Vector `json:"embedding"`
}

type InsertChunkRow struct {
	ChunkID    uuid.UUID       `json:"chunk_id"`
	FileID     uuid.UUID       `json:"file_id"`
	SubjectID  uuid.UUID       `json:"subject_id"`
	PageNumber sql.NullInt32   `json:"page_number"`
	ChunkIndex int32           `json:"chunk_index"`
	Content    string          `json:"content"`
	Embedding  pgvector.Vector `json:"embedding"`
	CreatedAt  time.Time       `json:"created_at"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (InsertChunkRow, error) {
	row := q.db.QueryRowContext(ctx, insertChunk,
		arg.ChunkID,
		arg.FileID,
		arg.ChunkIndex,
		arg.PageNumber,
		arg.Content,
		arg.Embedding,
	)
	var i InsertChunkRow
	err := row.Scan(
		&i.ChunkID,
		&i.FileID,
		&i.SubjectID,
		&i.PageNumber,
		&i.ChunkIndex,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const listChunksByFileID = `-- name: ListChunksByFileID :many

SELECT
  m.id AS chunk_id,
  m.raw_file_id AS file_id,
  rf.subject_id,
  m.page_start AS page_number,
  m.sequence_in_file AS chunk_index,
  m.content_markdown AS content,
  m.embedding,
  m.created_at
FROM materials m
JOIN raw_files rf ON rf.id = m.raw_file_id
WHERE m.raw_file_id = $1
  AND m.is_active = TRUE
ORDER BY m.sequence_in_file
`

type ListChunksByFileIDRow struct {
	ChunkID    uuid.UUID       `json:"chunk_id"`
	FileID     uuid.UUID       `json:"file_id"`
	SubjectID  uuid.UUID       `json:"subject_id"`
	PageNumber sql.NullInt32   `json:"page_number"`
	ChunkIndex int32           `json:"chunk_index"`
	Content    string          `json:"content"`
	Embedding  pgvector.Vector `json:"embedding"`
	CreatedAt  time.Time       `json:"created_at"`
}

// sql/queries/chunks.sql
func (q *Queries) ListChunksByFileID(ctx context.Context, rawFileID uuid.UUID) ([]ListChunksByFileIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listChunksByFileID, rawFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChunksByFileIDRow
	for rows.Next() {
		var i ListChunksByFileIDRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FileID,
			&i.SubjectID,
			&i.PageNumber,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChunksByText = `-- name: SearchChunksByText :many
SELECT
  m.id AS chunk_id,
  m.raw_file_id AS file_id,
  rf.subject_id,
  rf.original_filename AS file_name,
  m.page_start AS page_number,
  m.sequence_in_file AS chunk_index,
  m.content_markdown AS content,
  m.created_at
FROM materials m
JOIN raw_files rf ON rf.id = m.raw_file_id
WHERE rf.subject_id = $2
  AND rf.is_active = TRUE
  AND m.is_active = TRUE
  AND to_tsvector('simple', m.content_markdown) @@ plainto_tsquery('simple', $1)
ORDER BY ts_rank(to_tsvector('simple', m.content_markdown), plainto_tsquery('simple', $1)) DESC
LIMIT $3
`

type SearchChunksByTextParams struct {
	PlaintoTsquery string    `json:"plainto_tsquery"`
	SubjectID      uuid.UUID `json:"subject_id"`
	Limit          int32     `json:"limit"`
}

type SearchChunksByTextRow struct {
	ChunkID    uuid.UUID     `json:"chunk_id"`
	FileID     uuid.UUID     `json:"file_id"`
	SubjectID  uuid.UUID     `json:"subject_id"`
	FileName   string        `json:"file_name"`
	PageNumber sql.NullInt32 `json:"page_number"`
	ChunkIndex int32         `json:"chunk_index"`
	Content    string        `json:"content"`
	CreatedAt  time.Time     `json:"created_at"`
}

func (q *Queries) SearchChunksByText(ctx context.Context, arg SearchChunksByTextParams) ([]SearchChunksByTextRow, error) {
	rows, err := q.db.QueryContext(ctx, searchChunksByText, arg.PlaintoTsquery, arg.SubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksByTextRow
	for rows.Next() {
		var i SearchChunksByTextRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FileID,
			&i.SubjectID,
			&i.FileName,
			&i.PageNumber,
			&i.ChunkIndex,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChunksByVector = `-- name: SearchChunksByVector :many
SELECT
  m.id AS chunk_id,
  m.raw_file_id AS file_id,
  rf.subject_id,
  rf.original_filename AS file_name,
  m.page_start AS page_number,
  m.sequence_in_file AS chunk_index,
  m.content_markdown AS content,
  m.created_at
FROM materials m
JOIN raw_files rf ON rf.id = m.raw_file_id
WHERE rf.subject_id = $2
  AND rf.is_active = TRUE
  AND m.is_active = TRUE
ORDER BY m.embedding <=> $1::vector
LIMIT $3
`

type SearchChunksByVectorParams struct {
	Column1   pgvector.Vector `json:"column_1"`
	SubjectID uuid.UUID       `json:"subject_id"`
	Limit     int32           `json:"limit"`
}

type SearchChunksByVectorRow struct {
	ChunkID    uuid.UUID     `json:"chunk_id"`
	FileID     uuid.UUID     `json:"file_id"`
	SubjectID  uuid.UUID     `json:"subject_id"`
	FileName   string        `json:"file_name"`
	PageNumber sql.NullInt32 `json:"page_number"`
	ChunkIndex int32         `json:"chunk_index"`
	Content    string        `json:"content"`
	CreatedAt  time.Time     `json:"created_at"`
}

func (q *Queries) SearchChunksByVector(ctx context.Context, arg SearchChunksByVectorParams) ([]SearchChunksByVectorRow, error) {
	rows, err := q.db.QueryContext(ctx, searchChunksByVector, arg.Column1, arg.SubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksByVectorRow
	for rows.Next() {
		var i SearchChunksByVectorRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FileID,
			&i.SubjectID,
			&i.FileName,
			&i.PageNumber,
			&i.ChunkIndex,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
