// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createIngestJob = `-- name: CreateIngestJob :one

INSERT INTO jobs (id, target_raw_file_id, status, max_retries, idempotency_key, job_type)
VALUES ($1, $2, $3, $4, $5, 'file_ingestion')
RETURNING
  id AS job_id,
  target_raw_file_id AS file_id,
  status,
  retry_count,
  max_retries,
  error_message,
  created_at,
  started_at,
  completed_at
`

type CreateIngestJobParams struct {
	ID              uuid.UUID     `json:"id"`
	TargetRawFileID uuid.NullUUID `json:"target_raw_file_id"`
	Status          JobStatus     `json:"status"`
	MaxRetries      int32         `json:"max_retries"`
	IdempotencyKey  string        `json:"idempotency_key"`
}

type CreateIngestJobRow struct {
	JobID        uuid.UUID      `json:"job_id"`
	FileID       uuid.NullUUID  `json:"file_id"`
	Status       JobStatus      `json:"status"`
	RetryCount   int32          `json:"retry_count"`
	MaxRetries   int32          `json:"max_retries"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
}

// sql/queries/ingest_jobs.sql
func (q *Queries) CreateIngestJob(ctx context.Context, arg CreateIngestJobParams) (CreateIngestJobRow, error) {
	row := q.db.QueryRowContext(ctx, createIngestJob,
		arg.ID,
		arg.TargetRawFileID,
		arg.Status,
		arg.MaxRetries,
		arg.IdempotencyKey,
	)
	var i CreateIngestJobRow
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIngestJobByFileID = `-- name: GetIngestJobByFileID :one
SELECT
  id AS job_id,
  target_raw_file_id AS file_id,
  status,
  retry_count,
  max_retries,
  error_message,
  created_at,
  started_at,
  completed_at
FROM jobs
WHERE target_raw_file_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetIngestJobByFileIDRow struct {
	JobID        uuid.UUID      `json:"job_id"`
	FileID       uuid.NullUUID  `json:"file_id"`
	Status       JobStatus      `json:"status"`
	RetryCount   int32          `json:"retry_count"`
	MaxRetries   int32          `json:"max_retries"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
}

func (q *Queries) GetIngestJobByFileID(ctx context.Context, targetRawFileID uuid.NullUUID) (GetIngestJobByFileIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIngestJobByFileID, targetRawFileID)
	var i GetIngestJobByFileIDRow
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIngestJobByID = `-- name: GetIngestJobByID :one
SELECT
  id AS job_id,
  target_raw_file_id AS file_id,
  status,
  retry_count,
  max_retries,
  error_message,
  created_at,
  started_at,
  completed_at
FROM jobs
WHERE id = $1
`

type GetIngestJobByIDRow struct {
	JobID        uuid.UUID      `json:"job_id"`
	FileID       uuid.NullUUID  `json:"file_id"`
	Status       JobStatus      `json:"status"`
	RetryCount   int32          `json:"retry_count"`
	MaxRetries   int32          `json:"max_retries"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
}

func (q *Queries) GetIngestJobByID(ctx context.Context, id uuid.UUID) (GetIngestJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIngestJobByID, id)
	var i GetIngestJobByIDRow
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateIngestJobStatus = `-- name: UpdateIngestJobStatus :one
UPDATE jobs
SET
  status = $2,
  error_message = $3,
  started_at = CASE WHEN $2::job_status = 'processing' THEN NOW() ELSE started_at END,
  completed_at = CASE WHEN $2::job_status IN ('completed', 'failed', 'cancelled') THEN NOW() ELSE completed_at END,
  retry_count = CASE WHEN $2::job_status = 'failed' THEN retry_count + 1 ELSE retry_count END,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id AS job_id,
  target_raw_file_id AS file_id,
  status,
  retry_count,
  max_retries,
  error_message,
  created_at,
  started_at,
  completed_at
`

type UpdateIngestJobStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       JobStatus      `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

type UpdateIngestJobStatusRow struct {
	JobID        uuid.UUID      `json:"job_id"`
	FileID       uuid.NullUUID  `json:"file_id"`
	Status       JobStatus      `json:"status"`
	RetryCount   int32          `json:"retry_count"`
	MaxRetries   int32          `json:"max_retries"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
}

func (q *Queries) UpdateIngestJobStatus(ctx context.Context, arg UpdateIngestJobStatusParams) (UpdateIngestJobStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateIngestJobStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i UpdateIngestJobStatusRow
	err := row.Scan(
		&i.JobID,
		&i.FileID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
