// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qa_sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countQASessionsBySubjectID = `-- name: CountQASessionsBySubjectID :one
SELECT COUNT(*)
FROM chats
WHERE subject_id = $1
  AND user_id = $2
  AND is_active = TRUE
`

type CountQASessionsBySubjectIDParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CountQASessionsBySubjectID(ctx context.Context, arg CountQASessionsBySubjectIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQASessionsBySubjectID, arg.SubjectID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQASession = `-- name: CreateQASession :one

INSERT INTO chats (id, user_id, subject_id, question)
VALUES ($1, $2, $3, $4)
RETURNING
  id AS session_id,
  user_id,
  subject_id,
  question,
  final_answer_markdown AS answer,
  evidence_snippets AS sources,
  COALESCE(CASE feedback WHEN 'good' THEN 1 WHEN 'bad' THEN -1 END, 0)::smallint AS feedback,
  created_at,
  completed_at AS answered_at
`

type CreateQASessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Question  string    `json:"question"`
}

type CreateQASessionRow struct {
	SessionID  uuid.UUID             `json:"session_id"`
	UserID     uuid.UUID             `json:"user_id"`
	SubjectID  uuid.UUID             `json:"subject_id"`
	Question   string                `json:"question"`
	Answer     sql.NullString        `json:"answer"`
	Sources    pqtype.NullRawMessage `json:"sources"`
	Feedback   int16                 `json:"feedback"`
	CreatedAt  time.Time             `json:"created_at"`
	AnsweredAt sql.NullTime          `json:"answered_at"`
}

// sql/queries/qa_sessions.sql
func (q *Queries) CreateQASession(ctx context.Context, arg CreateQASessionParams) (CreateQASessionRow, error) {
	row := q.db.QueryRowContext(ctx, createQASession,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.Question,
	)
	var i CreateQASessionRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SubjectID,
		&i.Question,
		&i.Answer,
		&i.Sources,
		&i.Feedback,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getQASessionByID = `-- name: GetQASessionByID :one
SELECT
  id AS session_id,
  user_id,
  subject_id,
  question,
  final_answer_markdown AS answer,
  evidence_snippets AS sources,
  COALESCE(CASE feedback WHEN 'good' THEN 1 WHEN 'bad' THEN -1 END, 0)::smallint AS feedback,
  created_at,
  completed_at AS answered_at
FROM chats
WHERE id = $1
  AND is_active = TRUE
`

type GetQASessionByIDRow struct {
	SessionID  uuid.UUID             `json:"session_id"`
	UserID     uuid.UUID             `json:"user_id"`
	SubjectID  uuid.UUID             `json:"subject_id"`
	Question   string                `json:"question"`
	Answer     sql.NullString        `json:"answer"`
	Sources    pqtype.NullRawMessage `json:"sources"`
	Feedback   int16                 `json:"feedback"`
	CreatedAt  time.Time             `json:"created_at"`
	AnsweredAt sql.NullTime          `json:"answered_at"`
}

func (q *Queries) GetQASessionByID(ctx context.Context, id uuid.UUID) (GetQASessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getQASessionByID, id)
	var i GetQASessionByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SubjectID,
		&i.Question,
		&i.Answer,
		&i.Sources,
		&i.Feedback,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getQASessionByIDAndUserID = `-- name: GetQASessionByIDAndUserID :one
SELECT
  id AS session_id,
  user_id,
  subject_id,
  question,
  final_answer_markdown AS answer,
  evidence_snippets AS sources,
  COALESCE(CASE feedback WHEN 'good' THEN 1 WHEN 'bad' THEN -1 END, 0)::smallint AS feedback,
  created_at,
  completed_at AS answered_at
FROM chats
WHERE id = $1
  AND user_id = $2
  AND is_active = TRUE
`

type GetQASessionByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetQASessionByIDAndUserIDRow struct {
	SessionID  uuid.UUID             `json:"session_id"`
	UserID     uuid.UUID             `json:"user_id"`
	SubjectID  uuid.UUID             `json:"subject_id"`
	Question   string                `json:"question"`
	Answer     sql.NullString        `json:"answer"`
	Sources    pqtype.NullRawMessage `json:"sources"`
	Feedback   int16                 `json:"feedback"`
	CreatedAt  time.Time             `json:"created_at"`
	AnsweredAt sql.NullTime          `json:"answered_at"`
}

func (q *Queries) GetQASessionByIDAndUserID(ctx context.Context, arg GetQASessionByIDAndUserIDParams) (GetQASessionByIDAndUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getQASessionByIDAndUserID, arg.ID, arg.UserID)
	var i GetQASessionByIDAndUserIDRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SubjectID,
		&i.Question,
		&i.Answer,
		&i.Sources,
		&i.Feedback,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const listQASessionsBySubjectID = `-- name: ListQASessionsBySubjectID :many
SELECT
  id AS session_id,
  user_id,
  subject_id,
  question,
  final_answer_markdown AS answer,
  evidence_snippets AS sources,
  COALESCE(CASE feedback WHEN 'good' THEN 1 WHEN 'bad' THEN -1 END, 0)::smallint AS feedback,
  created_at,
  completed_at AS answered_at
FROM chats
WHERE subject_id = $1
  AND user_id = $2
  AND is_active = TRUE
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListQASessionsBySubjectIDParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListQASessionsBySubjectIDRow struct {
	SessionID  uuid.UUID             `json:"session_id"`
	UserID     uuid.UUID             `json:"user_id"`
	SubjectID  uuid.UUID             `json:"subject_id"`
	Question   string                `json:"question"`
	Answer     sql.NullString        `json:"answer"`
	Sources    pqtype.NullRawMessage `json:"sources"`
	Feedback   int16                 `json:"feedback"`
	CreatedAt  time.Time             `json:"created_at"`
	AnsweredAt sql.NullTime          `json:"answered_at"`
}

func (q *Queries) ListQASessionsBySubjectID(ctx context.Context, arg ListQASessionsBySubjectIDParams) ([]ListQASessionsBySubjectIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listQASessionsBySubjectID,
		arg.SubjectID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQASessionsBySubjectIDRow
	for rows.Next() {
		var i ListQASessionsBySubjectIDRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.SubjectID,
			&i.Question,
			&i.Answer,
			&i.Sources,
			&i.Feedback,
			&i.CreatedAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQASessionAnswer = `-- name: UpdateQASessionAnswer :one
UPDATE chats
SET
  final_answer_markdown = $2,
  evidence_snippets = $3,
  completed_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND is_active = TRUE
RETURNING
  id AS session_id,
  user_id,
  subject_id,
  question,
  final_answer_markdown AS answer,
  evidence_snippets AS sources,
  COALESCE(CASE feedback WHEN 'good' THEN 1 WHEN 'bad' THEN -1 END, 0)::smallint AS feedback,
  created_at,
  completed_at AS answered_at
`

type UpdateQASessionAnswerParams struct {
	ID                  uuid.UUID             `json:"id"`
	FinalAnswerMarkdown sql.NullString        `json:"final_answer_markdown"`
	EvidenceSnippets    pqtype.NullRawMessage `json:"evidence_snippets"`
}

type UpdateQASessionAnswerRow struct {
	SessionID  uuid.UUID             `json:"session_id"`
	UserID     uuid.UUID             `json:"user_id"`
	SubjectID  uuid.UUID             `json:"subject_id"`
	Question   string                `json:"question"`
	Answer     sql.NullString        `json:"answer"`
	Sources    pqtype.NullRawMessage `json:"sources"`
	Feedback   int16                 `json:"feedback"`
	CreatedAt  time.Time             `json:"created_at"`
	AnsweredAt sql.NullTime          `json:"answered_at"`
}

func (q *Queries) UpdateQASessionAnswer(ctx context.Context, arg UpdateQASessionAnswerParams) (UpdateQASessionAnswerRow, error) {
	row := q.db.QueryRowContext(ctx, updateQASessionAnswer, arg.ID, arg.FinalAnswerMarkdown, arg.EvidenceSnippets)
	var i UpdateQASessionAnswerRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SubjectID,
		&i.Question,
		&i.Answer,
		&i.Sources,
		&i.Feedback,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const updateQASessionFeedback = `-- name: UpdateQASessionFeedback :one
UPDATE chats
SET
  feedback = CASE
    WHEN $2 = 1 THEN 'good'::chat_feedback
    WHEN $2 = -1 THEN 'bad'::chat_feedback
    ELSE feedback
  END,
  feedback_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND user_id = $3
  AND is_active = TRUE
RETURNING
  id AS session_id,
  user_id,
  subject_id,
  question,
  final_answer_markdown AS answer,
  evidence_snippets AS sources,
  COALESCE(CASE feedback WHEN 'good' THEN 1 WHEN 'bad' THEN -1 END, 0)::smallint AS feedback,
  created_at,
  completed_at AS answered_at
`

type UpdateQASessionFeedbackParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
	UserID  uuid.UUID   `json:"user_id"`
}

type UpdateQASessionFeedbackRow struct {
	SessionID  uuid.UUID             `json:"session_id"`
	UserID     uuid.UUID             `json:"user_id"`
	SubjectID  uuid.UUID             `json:"subject_id"`
	Question   string                `json:"question"`
	Answer     sql.NullString        `json:"answer"`
	Sources    pqtype.NullRawMessage `json:"sources"`
	Feedback   int16                 `json:"feedback"`
	CreatedAt  time.Time             `json:"created_at"`
	AnsweredAt sql.NullTime          `json:"answered_at"`
}

func (q *Queries) UpdateQASessionFeedback(ctx context.Context, arg UpdateQASessionFeedbackParams) (UpdateQASessionFeedbackRow, error) {
	row := q.db.QueryRowContext(ctx, updateQASessionFeedback, arg.ID, arg.Column2, arg.UserID)
	var i UpdateQASessionFeedbackRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.SubjectID,
		&i.Question,
		&i.Answer,
		&i.Sources,
		&i.Feedback,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}
