// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, owner_user_id, title, course_code)
VALUES ($1, $2, $3, $4)
RETURNING
  id AS subject_id,
  owner_user_id AS user_id,
  title AS name,
  course_code AS lms_course_id,
  created_at,
  updated_at
`

type CreateSubjectParams struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
}

type CreateSubjectRow struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (CreateSubjectRow, error) {
	row := q.db.QueryRowContext(ctx, createSubject,
		arg.SubjectID,
		arg.UserID,
		arg.Name,
		arg.LmsCourseID,
	)
	var i CreateSubjectRow
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
UPDATE subjects
SET is_active = FALSE,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND owner_user_id = $2
  AND is_active = TRUE
`

type DeleteSubjectParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSubject(ctx context.Context, arg DeleteSubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, arg.SubjectID, arg.UserID)
	return err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT
  id AS subject_id,
  owner_user_id AS user_id,
  title AS name,
  course_code AS lms_course_id,
  created_at,
  updated_at
FROM subjects
WHERE id = $1
  AND is_active = TRUE
`

type GetSubjectByIDRow struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (GetSubjectByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByID, id)
	var i GetSubjectByIDRow
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectByIDAndUserID = `-- name: GetSubjectByIDAndUserID :one
SELECT
  id AS subject_id,
  owner_user_id AS user_id,
  title AS name,
  course_code AS lms_course_id,
  created_at,
  updated_at
FROM subjects
WHERE id = $1
  AND owner_user_id = $2
  AND is_active = TRUE
`

type GetSubjectByIDAndUserIDParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

type GetSubjectByIDAndUserIDRow struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) GetSubjectByIDAndUserID(ctx context.Context, arg GetSubjectByIDAndUserIDParams) (GetSubjectByIDAndUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByIDAndUserID, arg.ID, arg.OwnerUserID)
	var i GetSubjectByIDAndUserIDRow
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectsByUserID = `-- name: ListSubjectsByUserID :many

SELECT
  id AS subject_id,
  owner_user_id AS user_id,
  title AS name,
  course_code AS lms_course_id,
  created_at,
  updated_at
FROM subjects
WHERE owner_user_id = $1
  AND is_active = TRUE
ORDER BY created_at DESC
`

type ListSubjectsByUserIDRow struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// sql/queries/subjects.sql
func (q *Queries) ListSubjectsByUserID(ctx context.Context, ownerUserID uuid.UUID) ([]ListSubjectsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsByUserID, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectsByUserIDRow
	for rows.Next() {
		var i ListSubjectsByUserIDRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.UserID,
			&i.Name,
			&i.LmsCourseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubjectName = `-- name: UpdateSubjectName :one
UPDATE subjects
SET title = $1,
    updated_at = NOW()
WHERE id = $2
  AND owner_user_id = $3
  AND is_active = TRUE
RETURNING
  id AS subject_id,
  owner_user_id AS user_id,
  title AS name,
  course_code AS lms_course_id,
  created_at,
  updated_at
`

type UpdateSubjectNameParams struct {
	Name      string    `json:"name"`
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type UpdateSubjectNameRow struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	LmsCourseID sql.NullString `json:"lms_course_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateSubjectName(ctx context.Context, arg UpdateSubjectNameParams) (UpdateSubjectNameRow, error) {
	row := q.db.QueryRowContext(ctx, updateSubjectName, arg.Name, arg.SubjectID, arg.UserID)
	var i UpdateSubjectNameRow
	err := row.Scan(
		&i.SubjectID,
		&i.UserID,
		&i.Name,
		&i.LmsCourseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
