// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, email, provider, provider_user_id)
VALUES ($1, $2, $3, $4)
RETURNING user_id, email, provider, provider_user_id, created_at, updated_at
`

type CreateUserParams struct {
	UserID         uuid.UUID        `json:"user_id"`
	Email          string           `json:"email"`
	Provider       NullAuthProvider `json:"provider"`
	ProviderUserID sql.NullString   `json:"provider_user_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Provider,
		arg.ProviderUserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, provider, provider_user_id, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT user_id, email, provider, provider_user_id, created_at, updated_at
FROM users
WHERE user_id = $1
`

// sql/queries/users.sql
func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email            = COALESCE($1, email),
    provider         = COALESCE($2, provider),
    provider_user_id = COALESCE($3, provider_user_id),
    updated_at       = NOW()
WHERE user_id = $4
RETURNING user_id, email, provider, provider_user_id, created_at, updated_at
`

type UpdateUserParams struct {
	Email          sql.NullString   `json:"email"`
	Provider       NullAuthProvider `json:"provider"`
	ProviderUserID sql.NullString   `json:"provider_user_id"`
	UserID         uuid.UUID        `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Provider,
		arg.ProviderUserID,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
