// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, provider, provider_user_id)
VALUES ($1, COALESCE($3, 'development'), COALESCE($4, $2))
RETURNING
  id AS user_id,
  provider,
  provider_user_id,
  created_at,
  updated_at
`

type CreateUserParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

type CreateUserRow struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id AS user_id,
  provider,
  provider_user_id,
  created_at,
  updated_at
FROM users
WHERE provider_user_id = $1
  AND is_active = TRUE
`

type GetUserByEmailRow struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, providerUserID string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, providerUserID)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT
  id AS user_id,
  provider,
  provider_user_id,
  created_at,
  updated_at
FROM users
WHERE id = $1
  AND is_active = TRUE
`

type GetUserByIDRow struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// sql/queries/users.sql
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  provider = COALESCE($1, provider),
  provider_user_id = COALESCE($2, provider_user_id),
  updated_at = NOW()
WHERE id = $3
RETURNING
  id AS user_id,
  provider,
  provider_user_id,
  created_at,
  updated_at
`

type UpdateUserParams struct {
	Provider       sql.NullString `json:"provider"`
	ProviderUserID sql.NullString `json:"provider_user_id"`
	UserID         uuid.UUID      `json:"user_id"`
}

type UpdateUserRow struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Provider, arg.ProviderUserID, arg.UserID)
	var i UpdateUserRow
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
